<?php

namespace Goksagun\SchedulerBundle\Repository;

/**
 * ScheduledTaskLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduledTaskLogRepository extends \Doctrine\ORM\EntityRepository
{
    use CrudTrait;
}
